# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcCalc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0egrpcCalc.proto\x12\x04main\"\x15\n\x06result\x12\x0b\n\x03num\x18\x01 \x01(\x05\"&\n\x04\x61rgs\x12\x0e\n\x06numOne\x18\x01 \x01(\x05\x12\x0e\n\x06numTwo\x18\x02 \x01(\x05\x32\x89\x01\n\x03\x61pi\x12\x1f\n\x03\x61\x64\x64\x12\n.main.args\x1a\x0c.main.result\x12\x1f\n\x03sub\x12\n.main.args\x1a\x0c.main.result\x12\x1f\n\x03mul\x12\n.main.args\x1a\x0c.main.result\x12\x1f\n\x03\x64iv\x12\n.main.args\x1a\x0c.main.resultb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpcCalc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESULT._serialized_start=24
  _RESULT._serialized_end=45
  _ARGS._serialized_start=47
  _ARGS._serialized_end=85
  _API._serialized_start=88
  _API._serialized_end=225
# @@protoc_insertion_point(module_scope)
