version: '3'
services:
  mqtt-broker:
    image: eclipse-mosquitto:1.6.12
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_logs:/mosquitto/log
    environment:
      - MAX_MESSAGE_SIZE=100000000

volumes:
  mosquitto_data:
  mosquitto_logs:
